"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-08 11:18:45.204367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symbol_dictionary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('isa_type_code', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_crop_path', sa.String(length=1024), nullable=True),
    sa.Column('shape_signature', sa.JSON(), nullable=True),
    sa.Column('attributes_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name', name='uq_symbol_dictionary_category')
    )
    with op.batch_alter_table('symbol_dictionary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symbol_dictionary_category_name'), ['category_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbol_dictionary_isa_type_code'), ['isa_type_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbol_dictionary_source'), ['source'], unique=False)

    op.create_table('extraction_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('auto_learn_unknowns', sa.Boolean(), nullable=True),
    sa.Column('source_filenames', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extraction_jobs_status'), ['status'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=512), nullable=False),
    sa.Column('image_path', sa.String(length=1024), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_project_id'), ['project_id'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_project_id'), ['project_id'], unique=False)

    op.create_table('lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.String(length=128), nullable=True),
    sa.Column('line_type', sa.String(length=64), nullable=True),
    sa.Column('from_tag', sa.String(length=128), nullable=True),
    sa.Column('to_tag', sa.String(length=128), nullable=True),
    sa.Column('path_points', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lines_from_tag'), ['from_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_lines_line_number'), ['line_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_lines_line_type'), ['line_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_lines_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lines_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lines_to_tag'), ['to_tag'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_type', sa.String(length=32), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_type', sa.String(length=32), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('inferred_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_inferred_by'), ['inferred_by'], unique=False)
        batch_op.create_index('ix_relationships_project_page', ['project_id', 'page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index('ix_relationships_source_lookup', ['source_entity_id', 'source_entity_type'], unique=False)
        batch_op.create_index('ix_relationships_target_lookup', ['target_entity_id', 'target_entity_type'], unique=False)

    op.create_table('symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('class_name', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('extracted_text', sa.String(length=512), nullable=True),
    sa.Column('is_unknown', sa.Boolean(), nullable=True),
    sa.Column('resolved_from_unknown_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symbols_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbols_page_id'), ['page_id'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('equipment_type', sa.String(length=128), nullable=True),
    sa.Column('bbox_x1', sa.Float(), nullable=True),
    sa.Column('bbox_y1', sa.Float(), nullable=True),
    sa.Column('bbox_x2', sa.Float(), nullable=True),
    sa.Column('bbox_y2', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_equipment_type'), ['equipment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_tag'), ['tag'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('isa_type_code', sa.String(length=16), nullable=True),
    sa.Column('instrument_type', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('connected_to', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_isa_type_code'), ['isa_type_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instruments_tag'), ['tag'], unique=False)

    op.create_table('unknown_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('symbol_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('bbox_x1', sa.Float(), nullable=False),
    sa.Column('bbox_y1', sa.Float(), nullable=False),
    sa.Column('bbox_x2', sa.Float(), nullable=False),
    sa.Column('bbox_y2', sa.Float(), nullable=False),
    sa.Column('crop_image_path', sa.String(length=1024), nullable=False),
    sa.Column('surrounding_text', sa.Text(), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('user_provided_category', sa.String(length=128), nullable=True),
    sa.Column('user_provided_attributes', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unknown_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unknown_symbols_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unknown_symbols_page_id'), ['page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unknown_symbols_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unknown_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unknown_symbols_status'))
        batch_op.drop_index(batch_op.f('ix_unknown_symbols_page_id'))
        batch_op.drop_index(batch_op.f('ix_unknown_symbols_job_id'))

    op.drop_table('unknown_symbols')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_tag'))
        batch_op.drop_index(batch_op.f('ix_instruments_project_id'))
        batch_op.drop_index(batch_op.f('ix_instruments_page_id'))
        batch_op.drop_index(batch_op.f('ix_instruments_isa_type_code'))

    op.drop_table('instruments')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_tag'))
        batch_op.drop_index(batch_op.f('ix_equipment_project_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_page_id'))
        batch_op.drop_index(batch_op.f('ix_equipment_equipment_type'))

    op.drop_table('equipment')
    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbols_page_id'))
        batch_op.drop_index(batch_op.f('ix_symbols_class_name'))

    op.drop_table('symbols')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_relationships_target_lookup')
        batch_op.drop_index('ix_relationships_source_lookup')
        batch_op.drop_index(batch_op.f('ix_relationships_relation_type'))
        batch_op.drop_index('ix_relationships_project_page')
        batch_op.drop_index(batch_op.f('ix_relationships_inferred_by'))

    op.drop_table('relationships')
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lines_to_tag'))
        batch_op.drop_index(batch_op.f('ix_lines_project_id'))
        batch_op.drop_index(batch_op.f('ix_lines_page_id'))
        batch_op.drop_index(batch_op.f('ix_lines_line_type'))
        batch_op.drop_index(batch_op.f('ix_lines_line_number'))
        batch_op.drop_index(batch_op.f('ix_lines_from_tag'))

    op.drop_table('lines')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_project_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_page_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_project_id'))
        batch_op.drop_index(batch_op.f('ix_pages_job_id'))

    op.drop_table('pages')
    with op.batch_alter_table('extraction_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_extraction_jobs_project_id'))

    op.drop_table('extraction_jobs')
    with op.batch_alter_table('symbol_dictionary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbol_dictionary_source'))
        batch_op.drop_index(batch_op.f('ix_symbol_dictionary_isa_type_code'))
        batch_op.drop_index(batch_op.f('ix_symbol_dictionary_category_name'))

    op.drop_table('symbol_dictionary')
    op.drop_table('projects')
    # ### end Alembic commands ###
